### ISSUE TITLE
Input method behaviour

### ISSUE THREAD

**Issue by A6GibKm** [masm11/emacs#43]
One of the goals of Wayland is to be transparent to the user, user facing features should not be different from their X counterpart.

On vanilla `emacs -Q` 26.3, pressing  `´ a` results in  `á` on a spanish (Latin America) keyboard, the interface does not tell the user it is waiting after the prefix key `´` has been pressed, this last part is not consistence with the global experience in gtk, where you see, for example
![image](https://user-images.githubusercontent.com/11528996/90314750-a5571680-df05-11ea-87b9-9a92490b8b55.png)
(note the underline) on firefox or other gtk apps, when waiting for a key after the prefix `´`.

On the  `pgtk`  branch, pressing `´ a`  on `emacs -Q` wrongly inserts `a`. Adding 
```lisp
(when (eq window-system 'pgtk)
  (pgtk-use-im-context t))
```
Does fix the issue, `´ a` results in  `á` ,  and the behaviour is the expected one for a gtk app (the screenshot above is from pgtk Emacs).

## Suggestion

Since the default emacs behaviour is to recognize `á`, and the expected gtk behaviour is to recognize these bindings and to show this "waiiting" as in the screenshot, `(pgtk-use-im-context t)` should be set as the default.

My suggestion is to add a variable, named similarly to `pgtk-use-im-context`, to enable `(pgtk-use-im-context t)` at startup, this variable is set to `t` by default. From my experience, this kind of behaviours are generally handled via variables instead of functions, but as long as the defaults are what they should be expected it does not matter how this is implemented.

**P.S.** This is the one remaining difference (regression) I can notice from vanilla Emacs, thanks for your great work.

**Comment by masm11** [comment]
WIth pgtk-use-im-context, he in #30 seems not to be able to use reverse-im.el.  Should he disable pgtk-use-im-context explicitly?

EDIT:
Most people in the world don't need GtkIMContext.  Some people think GtkIMContext is in the way.
So I think GtkIMContext should be disabled by default.

**Comment by A6GibKm** [comment]
Fair enough. How does vanilla emacs provide this basic support for prefix keys? I just hope pgtk to not introduce regressions.

**Comment by masm11** [comment]
[Here](https://github.com/masm11/emacs/blob/c054286084a3eba16f6ccd26b063dfa6cb2da4a9/src/xterm.c#L8489),
if the frame has XIC, then XmbLookupString is used.
Otherwise, XLookupString is used.

For you, XLookupString is suitable.
For he, XmbLookupString is suitable, maybe.

XLookupString takes compose_status as the last argument, which must be for you.

And, how to decide whether the frame should have XIC.

It is set [here](https://github.com/masm11/emacs/blob/c054286084a3eba16f6ccd26b063dfa6cb2da4a9/src/xfns.c#L2740) in create_frame_xic, which is called from [here](https://github.com/masm11/emacs/blob/c054286084a3eba16f6ccd26b063dfa6cb2da4a9/src/xfns.c#L3196) only when use_xim is true.

use_xim is set around [here](https://github.com/masm11/emacs/blob/c054286084a3eba16f6ccd26b063dfa6cb2da4a9/src/xterm.c#L137) and [here](https://github.com/masm11/emacs/blob/c054286084a3eba16f6ccd26b063dfa6cb2da4a9/src/xterm.c#L13213). It is controlled by configure option and X resources.

Maybe your use_xim and his are different.
pgtk doesn't have use_xim. Instead it has pgtk-use-im-context.

**Comment by ghost** [comment]
@masm11 
> WIth pgtk-use-im-context, he in #30 seems not to be able to use reverse-im.el.

No-no it works as it should after you patched it. And actually I don't see why it should be disabled by default, but maybe I miss something.

**Comment by masm11** [comment]
@Svadkos Thanks for the comment.

@A6GibKm I'll change to enable by default.

**Comment by A6GibKm** [comment]
Tested #44 and it is indeed enabled by default :+1: . I have a unrelated question, I was looking at this [emacs-devel thread](https://lists.gnu.org/archive/html/emacs-devel/2020-04/msg01741.html), are there plans to allow building against gtk4? the most interesting feature is the gpu acceleration, which as far as I know can be only be achieved in emacs using this [PR](https://github.com/remacs/remacs/pull/1581) at [remacs](https://github.com/remacs/remacs/).

**Comment by masm11** [comment]
Thanks for the testing, but it needs more code.

Po Lu is developing Gtk4 support.

If I apply his patch and push to here, the code becomes mine.
I don't hope that.  His code should be his.

If he makes a PR for my fork, I'll want to accept it.
When he emailed me recently, I asked him that, but he didn't.
He may want to work on fsf's repo after we (I and fejfighter) push to fsf's repo.

**Comment by masm11** [comment]
#44 is done. could you test again?

**Comment by A6GibKm** [comment]
Done, works. The env variable also correctly disables IM when set to `nil`. Yo might want to update the README.md.

**Comment by masm11** [comment]
Thanks for the testing.
I'm sorry that I forgot to notice about the new variable.

I also updated README.md.
